mod simple;
pub(crate) mod ruff;
pub(crate) mod pylint;
pub(crate) mod pytest;
pub(crate) mod black;
pub(crate) mod doctest;
pub(crate) mod mypy;
pub(crate) mod pyrefly;
pub(crate) mod rumdl;
pub(crate) mod yamllint;
pub(crate) mod jq;
pub(crate) mod jsonlint;
pub(crate) mod taplo;
pub(crate) mod eslint;
pub(crate) mod jshint;
pub(crate) mod htmlhint;
pub(crate) mod stylelint;
pub(crate) mod checkstyle;
pub(crate) mod cmake;
pub(crate) mod hadolint;
pub(crate) mod htmllint;
pub(crate) mod jslint;
pub(crate) mod perlcritic;
pub(crate) mod php_lint;
pub(crate) mod slidev;
pub(crate) mod standard;
pub(crate) mod svglint;
pub(crate) mod tidy;
pub(crate) mod xmllint;
pub(crate) mod yq;
pub(crate) mod cppcheck;
pub(crate) mod cpplint;
pub(crate) mod checkpatch;
pub(crate) mod shellcheck;
pub(crate) mod luacheck;

mod aspell;
mod ascii;
mod clippy;
mod clang_tidy;
mod duplicate_files;
mod encoding;
mod license_header;
mod make;
mod marp_images;
mod markdownlint;
mod mdl;
mod script;
mod zspell;
mod ijq;
mod ijsonlint;
mod itaplo;
mod iyamllint;
mod iyamlschema;
mod json_schema;
pub(crate) mod terms;

